services:
  db:
    image: postgres:18.1-trixie
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: c4_events
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  mock-oauth2:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    restart: always
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      JSON_CONFIG_PATH: /config/config.json
    volumes:
      - ./mock-oauth2:/config

volumes:
  pgdata:
